function headerstable = DT_input_schema()
% Column identifiers only. This file contains no measurements.
rows = { ...
    'day', 'day'; ...
    'VCD_e6_', 'Xv'; ...
    'Glucose_g_L_', 'Glc'; ...
    'Lactate_g_L_', 'Lac'; ...
    'BRXTiter_mg_mL_', 'mAb'; ...
    'Glutamate_mmol_L_', 'Glu'; ...
    'Glutamine_mmol_L_', 'Gln'; ...
    'K__mmol_L_', 'K'; ...
    'Na__mmol_L_', 'Na'; ...
    'NH4__mmol_L_', 'NH4'; ...
    'L_AsparticAcid', 'Asp'; ...
    'L_Threonine', 'Thr'; ...
    'L_Serine', 'Ser'; ...
    'L_Asparagine', 'Asn'; ...
    'L_GlutamicAcid', 'GluAA'; ...
    'L_Glutamine', 'GlnAA'; ...
    'L_Cysteine', 'Cys'; ...
    'L_Proline', 'Pro'; ...
    'L_Glycine', 'Gly'; ...
    'L_Alanine', 'Ala'; ...
    'L_Valine', 'Val'; ...
    'L_Methionine', 'Met'; ...
    'L_Cystine', 'Cystine'; ...
    'L_Isoleucine', 'Ile'; ...
    'L_Leucine', 'Leu'; ...
    'L_Tyrosine', 'Tyr'; ...
    'L_Phenylalanine', 'Phe'; ...
    'Ethanolamine', 'Eth'; ...
    'L_Tryptophan', 'Trp'; ...
    'L_Lysine', 'Lys'; ...
    'L_Histidine', 'His'; ...
    'L_Arginine', 'Arg'; ...
    'G0F_Permeate_', 'G0F'; ...
    'G1F_Permeate_', 'G1F'; ...
    'G2F_Permeate_', 'G2F'; ...
    'FlowrateBleed', 'q4'; ...
    'FlowrateHarvest', 'q2'; ...
    'FlowrateFeed', 'q1'; ...
    'GlucoseFeed', 'q3'; ...
    'FlowrateFeed2', 'q5'; ...
    'FlowrateFeed3', 'q6'; ...
    'Recycle', 'q7'; ...
    'Man5F_Permeate_', 'M5F'; ...
    'G0F_Lys_Permeate_', 'G0FL'; ...
    'G0_Permeate_', 'G0'; ...
};
headerstable = cell2table(rows, 'VariableNames', {'Header','name'});
end
