% Manuscript code distribution. See docs/REPRODUCIBILITY_STATUS.md.
function rate = DT_kinetic(K_kinetic,Xv,Glc,Lac)
% This function makes a timetable without nans
% Inputs:
% values: a vector of values
% times: a vector of times
% Outputs:
% ts: a timetable with no nans
% Author: Zhao Wang, UMass Lowell, zhao_wang@student.uml.edu,2025

arguments
    K_kinetic
    Xv
    Glc
    Lac
end

% Unpack the parameters
% list of parameters: umaxglc umaxlac udmaxs udmaxt	kilac	kiglc	kglc	klac	kdlac	kdglc	Yxvglc	mglc	Ymabxv	YmabxvB Ylacglc	Yxvlac
umaxglc = K_kinetic.umaxglc/24; % convert 1/day to 1/hour
umaxlac = K_kinetic.umaxlac/24; % convert 1/day to 1/hour
udmaxs = K_kinetic.udmaxs/24; % convert 1/day to 1/hour
udmaxt = K_kinetic.udmaxt/24; % convert 1/day to 1/hour
kglc = K_kinetic.kglc;
klac = K_kinetic.klac;
kiglc = K_kinetic.kiglc;
kilac = K_kinetic.kilac;
Ylacglc = K_kinetic.Ylacglc;
Ymabxv = K_kinetic.Ymabxv;
YmabxvB = K_kinetic.YmabxvB/24; % convert 1/day to 1/hour
Yxvglc = K_kinetic.Yxvglc;
mglc = K_kinetic.mglc/24; % convert 1/day to 1/hour
Yxvlac = K_kinetic.Yxvlac;
kdglc = K_kinetic.kdglc;
kdlac = K_kinetic.kdlac;


% Kinetic models for reactions
    ug = umaxglc * Glc/(kglc + Glc) * kilac/(kilac + Lac);
    ul = umaxlac * Lac/(klac + Lac) * kiglc/(Glc + kiglc);
    u = ug + ul;

    udstarv = udmaxs  * kdglc/(Glc + kdglc);
    udtoxic = udmaxt * Lac/(kdlac + Lac);
    ud = udstarv+udtoxic;

    mu = u - ud;
    qglc = (ug / Yxvglc) + mglc;

    mYglclac = (Ylacglc * (ug / umaxglc)) * (ug / Yxvglc);
    mYxvlac = ul/Yxvlac;  %Lactate consumed by cell growth at low glucose
    qlac = mYglclac - mYxvlac;   %Lactate generated by glucose generation and consumption by cell growth
    qmab = u * Ymabxv + YmabxvB;
    %reactions for concentrations
    rXv = mu * Xv;
    rGlc = -qglc * Xv;
    rLac = qlac * Xv;
    rmab = qmab * Xv;
    
    % u = umax * Glc/(kglc + Glc);
    % ud = udmax * Lac/(kdlac + Lac) * kdglc/(kdglc + Glc);
    % qglc = (mu / Yxvglc) + mglc;
    %qlac = Ylacglc * qglc - (mu / Yxvlac);
rate = struct();
rate.rXv = rXv;
rate.rGlc = rGlc;
rate.rLac = rLac;
rate.rmab = rmab;
end
